/****** Скрипт для команды SelectTopNRows из среды SSMS ******/ 
SELECT TOP (1000) [IDApplication] 
,[ApplicationNumber] 
,[NeedHostel] 
,[IsInvalid] 
,[IDPerson] 
,[LastName] 
,[FirstName] 
,[MiddleName] 
,P.cSotTel 
,P.ctelefon 
,[IDGender] 
,[DateBirth] 
,[IDCompetitiveGroup] 
,[CompetitiveGroup] 
,[IDTargetOrganization] 
,[TargetOrganization] 
,[DateRegistration] 
,[AverMark] 
,[IDStateZachFIS] 
,[StateZach] 
,[IDDirection] 
,[Direction] 
,[IDTypeDirection] 
,[TypeDirection] 
,[IDDirectionFIS] 
,[IDFormEducation] 
,[IDFormEducationFIS] 
,[FormEducation] 
,[IDFaculty] 
,[Faculty] 
,[FacultyShort] 
,[IDSpeciality] 
,[IDSpecialityFIS] 
,[Speciality] 
,[SpecialityShort] 
,[IDNationality] 
,[Nationality] 
,[IDCategoryZach] 
,[CategoryZach] 
,[IDCategoryZachBenefit] 
,[IDTypeCategoryZach] 
,[TypeCategoryZach] 
,[JournalIsActual] 
,[Year] 
,[IDOrder] 
FROM [UGTU].[FIS].[ApplicationView] A inner join dbo.Person P on A.[IDPerson] = P.nCode 
where IDStateZachFIS = 8 and [Year] = 2017 and IDFaculty = 29 and IDSpecialityFIS in (17424) and IDGender = 0
order by [LastName]